name: Sync package.json with repository info

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install
        run: npm ci
        
      - name: Test
        run: npm t

      - name: Build
        run: npm run build
